# load pytorch, you can choose the appropriate tag based on your needs, e.g., with or without CUDA
FROM pytorch/pytorch:1.12.0-cuda11.3-cudnn8-runtime


# clone the repo 
RUN git clone https://github.com/your_username/your_repository.git


# Install any needed packages specified in requirements.txt
#COPY requirements.txt /app/requirements.txt
#RUN pip install --no-cache-dir -r requirements.txt

# Install any additional system dependencies (optional)
#RUN apt-get update && apt-get install -y \
    #vim \
    #&& rm -rf /var/lib/apt/lists/*

# Set environment variables (optional)
#ENV PYTHONUNBUFFERED=1

# Specify the command to run on container start (optional)
#CMD ["python", "inference.py"]

# Expose port (if needed for services like web applications)
# EXPOSE 8000

